### ISSUE TITLE
pc screen blue

### ISSUE THREAD

**Issue by crystalpvpnn** [Chachoox/SexMaster.CC-Rewrite#1]
my pc screen turned blue after running this pls help
![image](https://github.com/Chachoox/SexMaster.CC-Rewrite/assets/111325757/d3dfc22f-73d1-459f-a7ab-aabaa615d83b)

**Comment by pycnocarpa** [comment]
How tf you figured out how to make a github account

**Comment by crystalpvpnn** [comment]
Idk

**Comment by pycnocarpa** [comment]
Go pv

**Comment by crystalpvpnn** [comment]
position 7 bruh

**Comment by pycnocarpa** [comment]
No more pv

**Comment by angeIll** [comment]
works on my machine 😊

**Comment by Chachoox** [comment]
user error
